Bump maven-failsafe-plugin version from 2.18.1 to 2.19.1, to solve NoClassDefFoundError
required for https://git.opendaylight.org/gerrit/#/c/39484/

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] archetypes-parent .................................. SUCCESS [  2.431 s]
[INFO] odl-model-project .................................. SUCCESS [  9.970 s]
[INFO] opendaylight-configfile-archetype .................. SUCCESS [  3.365 s]
[INFO] distribution-karaf-archetype ....................... SUCCESS [ 24.224 s]
[INFO] opendaylight-karaf-features-archetype .............. SUCCESS [02:12 min]
[INFO] opendaylight-startup-archetype ..................... FAILURE [05:31 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:23 min
[INFO] Finished at: 2016-06-14T14:25:26+02:00
[INFO] Final Memory: 50M/1025M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test (failsafe-integration-tests) on project opendaylight-startup-archetype: Execution failsafe-integration-tests of goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: projects/basic/project/basic/it/target/test-classes/it/pkg/it/BasicIT (wrong name: it/pkg/it/BasicIT)
[ERROR] at java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[ERROR] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[ERROR] at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[ERROR] at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:131)
[ERROR] at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:95)
[ERROR] at org.apache.maven.surefire.junit.JUnit3Provider.scanClassPath(JUnit3Provider.java:137)
[ERROR] at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:88)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] -> [Help 1]

Change-Id: I9d80dc095b21d1ef33e4da214d2399d778a902ac
Signed-off-by: Michael Vorburger <vorburger@redhat.com>