Remove mockito-all from dependencyManagement; use (only) mockito-core
mockito-all is bad, because it includes other libs (non-shaded), they
never intended it to be used from system with transitive dependency
management such as Maven; it can cause issues incl. fix
NoSuchMethodError: org.hamcrest.Matcher ...

also forbid future non-use of mockito-all via a new rule of
maven-enforcer-plugin; see
http://maven.apache.org/enforcer/enforcer-rules/bannedDependencies.html

Bug 7662 related
Change-Id: Id0da73a875cbb6de481782db1ccaadd6ac54ea6f
Signed-off-by: Michael Vorburger <vorburger@redhat.com>