Update patch set 2
Patch Set 2:

In fact, there 2.6.0 has an additional error issue:

java.lang.NoClassDefFoundError: org.xml.sax.helpers.DefaultHandler

which is addressed in 2.6.1, so I don't think we even want 2.6.0 ever

Patch-set: 2