Update patch set 2
Patch Set 2:

(1 comment)

An example of feature which needs this (the feature already expects 2.0.3): https://git.opendaylight.org/gerrit/61274
Sandbox job where run #9 fails (without this) and run #10 passes (with this patch): https://jenkins.opendaylight.org/sandbox/job/integration-multipatch-test-nitrogen/

> Can we get a heapdump

Looking at surefire log: https://logs.opendaylight.org/sandbox/jenkins091/integration-multipatch-test-nitrogen/9/patch_tester/distribution/features/singles/odl-integration-compatible-with-all/target/surefire-reports/org.opendaylight.odlparent.featuretest.SingleFeatureTest-output.txt.gz

I see it attempts to create the dump, but the kill command fails, and java_pid13162.hprof file does not make it into logs archive for some reason.
2017-08-07 13:30:05,948 | INFO  | 1c032c70f953/etc | fileinstall                      | 4 - org.apache.felix.fileinstall - 3.5.8 | Creating configuration from netconf.cfg
java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to java_pid13162.hprof ...
Heap dump file created [2800712458 bytes in 10.112 secs]
#
# java.lang.OutOfMemoryError: GC overhead limit exceeded
# -XX:OnOutOfMemoryError=""kill -3 %p""
#   Executing /bin/sh -c ""kill -3 13162""...
sh: kill -3 13162: command not found

Patch-set: 2
Label: Verified=0