Update patch set 2
Abandoned

abandoning because this apparently needs to upgraded with all of Scala, otherwise:

Running org.opendaylight.odlparent.featuretest.SingleFeatureTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.612 sec <<< FAILURE! - in org.opendaylight.odlparent.featuretest.SingleFeatureTest
installFeatureCatchAndLog(org.opendaylight.odlparent.featuretest.SingleFeatureTest)[repoUrl: file:/home/vorburger/dev/ODL/git/odlparent/features/odl-akka-clustering-2.5/target/feature/feature.xml, Feature: odl-akka-clustering-2.5 4.0.0.SNAPSHOT]  Time elapsed: 15.259 sec  <<< ERROR!
org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=odl-akka-clustering-2.5; type=karaf.feature; version="[4.0.0.SNAPSHOT,4.0.0.SNAPSHOT]"; filter:="(&(osgi.identity=odl-akka-clustering-2.5)(type=karaf.feature)(version>=4.0.0.SNAPSHOT)(version<=4.0.0.SNAPSHOT))" [caused by: Unable to resolve odl-akka-clustering-2.5/4.0.0.SNAPSHOT: missing requirement [odl-akka-clustering-2.5/4.0.0.SNAPSHOT] osgi.identity; osgi.identity=com.typesafe.akka.stream; type=osgi.bundle; version="[2.5.11,2.5.11]"; resolution:=mandatory [caused by: Unable to resolve com.typesafe.akka.stream/2.5.11: missing requirement [com.typesafe.akka.stream/2.5.11] osgi.wiring.package; filter:="(&(osgi.wiring.package=scala.util.parsing.combinator)(version>=1.0.4)(!(version>=1.1.0)))"]]

PS: Due to https://jira.opendaylight.org/browse/ODLPARENT-136 you need to add this to features/odl-akka-clustering-2.5/pom.xml to actually see the error above:

        <dependency>
            <groupId>org.osgi</groupId>
            <!-- required due to https://jira.opendaylight.org/browse/ODLPARENT-136 -->
            <artifactId>org.osgi.compendium</artifactId>
        </dependency>

Patch-set: 2
Status: abandoned
Tag: autogenerated:gerrit:abandon