Fix for improved Eclipse IDE setup: m2e's no longer explodes on import
Eclipse setup experience improvement #2.  More to come - much more.

java.lang.IllegalArgumentException: Missing parameter for
pluginExecutionFilter. groupId, artifactId, versionRange and goals must
be specificed, but found: groupId = 'null'
artifactId = 'maven-dependency-plugin'
versionRange = '[0.0,)'
goals = '[resolve]'
  at
org.eclipse.m2e.core.internal.lifecyclemapping.model.PluginExecutionFilter.checkAllFieldsSet(PluginExecutionFilter.java:320)

Change-Id: I43fe777e70fdb742e08e4b69d975423b203075ac
Signed-off-by: Michael Vorburger <vorburger@redhat.com>