Update patch set 2
Patch Set 2:

Actually it does not work with yangtools, throws:

initializationError(org.opendaylight.odlparent.featuretest.SingleFeatureTest)  Time elapsed: 0.027 sec  <<< ERROR!
org.ops4j.pax.exam.TestContainerException: java.lang.reflect.InvocationTargetException
        at java.net.URL.<init>(URL.java:600)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at org.opendaylight.odlparent.featuretest.SingleFeatureTest.standardKarafFeatures(SingleFeatureTest.java:167)
        at org.opendaylight.odlparent.featuretest.SingleFeatureTest.config(SingleFeatureTest.java:126)

It may be caused by pax-exam upgrade, which I am reverting.

Patch-set: 2