Update patch set 3
Patch Set 3:

> I have noticed the following interesting exception (present also in
 > previous pure-Beryllium run) in https://jenkins.opendaylight.org/releng/job/ovsdb-csit-1node-netvirt-only-beryllium/381/artifact/karaf.log
 > 
 > It probably means that downstream artifacts need to be rebuilt to
 > realize newer Jetty is to be used (meaning integration-patch-test-beryllium
 > is not enough to system test this change).
 > 
 > 2015-10-07 11:41:40,088 | WARN  | qtp1477061003-60 | ServletHandler
 >                   | 169 - org.eclipse.jetty.aggregate.jetty-all-server
 > - 8.1.15.v20140411 | Error for /controller/nb/v2/neutron/networks
 > java.lang.NoClassDefFoundError: javax/validation/ConstraintViolationException

This is fixed by https://git.opendaylight.org/gerrit/28016/ for the time being (the proper fix is to add a dependency on javax.validation:validation-api wherever eclipse.persistence is used).

Patch-set: 3