Revert "Bump maven-failsafe-plugin version from 2.18.1 to 2.19.1, to solve NoClassDefFoundError"
This reverts commit fb0e070b9c331b4487ee476673f5104e0d4f12d9.

Change-Id: Iecebc9322bf63c45355600536a66dae94cd58d8a
Signed-off-by: Robert Varga <rovarga@cisco.com>