Forbid use of mockito-all via a new maven-enforcer-plugin rule
mockito-all is bad, because it includes other libs (non-shaded), they
never intended it to be used from system with transitive dependency
management such as Maven; it can cause issues incl. fix
NoSuchMethodError: org.hamcrest.Matcher ...

see
http://maven.apache.org/enforcer/enforcer-rules/bannedDependencies.html

We'll remove mockito-all from dependencyManagement a little later.

Bug 7662 related
Change-Id: Id0da73a875cbb6de481782db1ccaadd6ac54ea6f
Signed-off-by: Michael Vorburger <vorburger@redhat.com>