Use python3 as basepython for docs
Python 2 is soon to be EOL and we've been having issues with it as of
late. Bump to Python 3 as the basepython to see if it helps with the
pytest issue:

ERROR: Package u'pytest' requires a different Python: 2.7.5 not in '>=3.5'

Issue: https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-17699
Signed-off-by: Thanh Ha <zxiiro@gmail.com>
Change-Id: Ie4c4547c9523ff5cf6c8d42e49a9514a07938e61