Update patch set 1
Patch Set 1:

> 2017-05-04 17:33:46,612 | ERROR | r - ConfigPusher | AbstractFeatureWrapper           | 43 - config-persister-feature4-adapter - 0.7.0.SNAPSHOT | Could not parse XML file /w/workspace/odlparent-distribution-check-nitrogen/karaf-0.7.0-SNAPSHOT/etc/opendaylight/karaf/10-rest-connector.xml
java.io.FileNotFoundException: /w/workspace/odlparent-distribution-check-nitrogen/karaf-0.7.0-SNAPSHOT/etc/opendaylight/karaf/10-rest-connector.xml (No such file or directory)

I do not think this Change has caused it. netconf-merge-nitrogen failed, but before upload phase. I restarted that anyway.

Patch-set: 1