WIP: Package aarch64
// FIXME: needs version substitution in conditionals
// FIXME: resolver barfs:

2025-04-04T15:11:08,997 | ERROR | RMI TCP Connection(4)-127.0.0.1 | TestProbe                        | 98 - PAXEXAM-PROBE-203e1264-9baf-4140-89b4-303bbe2ad3a6 - 0.0.0 | Exception executing feature test
java.lang.IllegalStateException: Resource io.netty.transport-native-epoll/4.1.119.Final is duplicated on subsystem root#odl-netty-4-14.0.9.SNAPSHOT. First resource requires [io.netty.transport-native-epoll/4.1.119.Final] osgi.identity; osgi.identity=odl-netty-4-condition-req_osgi_native_filter______osgi_native_osname__linux__osgi_native_processor__x86_64___; type=karaf.feature; version="[14.0.9.SNAPSHOT,14.0.9.SNAPSHOT]"; resolution:=mandatory while the second requires [io.netty.transport-native-epoll/4.1.119.Final] osgi.identity; osgi.identity=odl-netty-4-condition-req_osgi_native_filter______osgi_native_osname__linux__osgi_native_processor__AArch64___; type=karaf.feature; version="[14.0.9.SNAPSHOT,14.0.9.SNAPSHOT]"; resolution:=mandatory
        at org.apache.karaf.features.internal.region.Subsystem.merge(Subsystem.java:731) ~[?:?]
        at java.util.HashMap.merge(HashMap.java:1391) ~[?:?]
        at org.apache.karaf.features.internal.region.Subsystem.doAddDependency(Subsystem.java:713) ~[?:?]
        at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:591) ~[?:?]
        at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:469) ~[?:?]
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:223) ~[?:?]
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

Change-Id: I2a892355742a412f1690566d05296e06388a5162
Signed-off-by: Robert Varga <robert.varga@pantheon.tech>