Improve SFT TestBundleDiag under Karaf 4
This does NOT yet completely fix all problems of the SingleFeatureTest
TestBundleDiag under Karaf 4 (which was in really bad shape!), most
importantly there is still something somewhere in Pax Exam that I
haven't understood yet which seems to just "swallow" all exceptions
thrown by SingleFeatureTest's @Test installFeature(), but at least, now:

1. there is something in the log now for failures at least
   thanks to a (try/catch/log) WORKAROUND (!)

2. LinkageError fixed (see details below)

3. IllegalStateException: BundleContext is no longer valid fixed (?)

This changes the setup by just embedding bundles4-test and it's
dependencies into features4-test, instead of programmatically installing
the odl-bundles-test feature (which is removed in this change) or the
features4-test bundle.  

This simplifies installation, avoid problems with the wrap: protocol,
and should resolve weird problems we've seen (only!) in the distribution
jobs, which seem to have had something to do with a custom local Maven
repo.

IMHO it would be *REALLY* good to practice proper TDD for SFT (with
TestBundleDiag) now, and have some automated negative testing of broken
features and bundles (incl. BP) in odlparent...

Full details background re. 2. problem:

PAXEXAM-PROBE-e5319751-e0a5-42c1-a7bf-250eaaadeb37[org.opendaylight.odlparent.featuretest.SingleFeatureTest]
: installFeature() failed
java.util.concurrent.ExecutionException: java.lang.LinkageError: loader
constraint violation: loader (instance of
org/eclipse/osgi/internal/loader/EquinoxClassLoader) previously
initiated loading for a different type with name
"org/apache/karaf/bundle/core/BundleService"
         at java.util.concurrent.FutureTask.report(FutureTask.java:122)
         at java.util.concurrent.FutureTask.get(FutureTask.java:206)
(07:22:59  CET) vorburger:         at
org.awaitility.core.ConditionAwaiter$1.run(ConditionAwaiter.java:160)
(07:22:59  CET) vorburger:         at
java.lang.Thread.run(Thread.java:745)
(07:22:59  CET) vorburger: Caused by: java.lang.LinkageError: loader
constraint violation: loader (instance of
org/eclipse/osgi/internal/loader/EquinoxClassLoader) previously
initiated loading for a different type with name
"org/apache/karaf/bundle/core/BundleService"
(07:22:59  CET) vorburger:         at
org.opendaylight.odlparent.bundles4test.BundleDiagInfos.forContext(BundleDiagInfos.java:52)
(07:22:59  CET) vorburger:         at
org.opendaylight.odlparent.bundles4test.TestBundleDiag.getBundleDiagInfos(TestBundleDiag.java:107)
(07:22:59  CET) vorburger:         at
org.opendaylight.odlparent.bundles4test.TestBundleDiag.lambda$checkBundleDiagInfos$1(TestBundleDiag.java:62)
(07:22:59  CET) vorburger:         at
org.awaitility.core.AbstractHamcrestCondition$1.eval(AbstractHamcrestCondition.java:50)
(07:22:59  CET) vorburger:         at
org.awaitility.core.ConditionAwaiter$ConditionPoller.run(ConditionAwaiter.java:215)
(07:22:59  CET) vorburger:         at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
(07:22:59  CET) vorburger:         at
java.util.concurrent.FutureTask.run(FutureTask.java:266)
(07:22:59  CET) vorburger:         at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
(07:22:59  CET) vorburger:         at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
(07:22:59  CET) vorburger:         ... 1 more

Full details background re. 3. problem:

2017-03-09 18:35:49,250 | ERROR | 5cf-9e07492fd414 | core
| 8 - org.apache.karaf.features.core - 4.0.7 | FrameworkEvent ERROR -
org.apache.karaf.features.core
 org.osgi.framework.ServiceException: Exception in
org.eclipse.equinox.internal.region.hook.RegionBundleFindHook.find()
         at
org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHookPrivileged(ServiceRegistry.java:1288)
         at
org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHooksPrivileged(ServiceRegistry.java:1263)
         at
org.eclipse.osgi.internal.framework.BundleContextImpl.notifyFindHooksPriviledged(BundleContextImpl.java:224)
         at
org.eclipse.osgi.internal.framework.BundleContextImpl.notifyFindHooks(BundleContextImpl.java:209)
         at
org.eclipse.osgi.internal.framework.BundleContextImpl.getBundles(BundleContextImpl.java:197)
         at
org.opendaylight.odlparent.bundles4test.BundleDiagInfos.forContext(BundleDiagInfos.java:50)
         at
org.opendaylight.odlparent.bundles4test.TestBundleDiag.getBundleDiagInfos(TestBundleDiag.java:106)
         at
org.opendaylight.odlparent.bundles4test.TestBundleDiag.lambda$checkBundleDiagInfos$1(TestBundleDiag.java:61)
         at
org.awaitility.core.AbstractHamcrestCondition$1.eval(AbstractHamcrestCondition.java:50)[77:wrap_file__home_vorburger_.m2_repository_org_awaitility_awaitility_2.0.0_awaitility-2.0.0.jar:0.0.0]
         at
org.awaitility.core.ConditionAwaiter$ConditionPoller.run(ConditionAwaiter.java:215)[77:wrap_file__home_vorburger_.m2_repository_org_awaitility_awaitility_2.0.0_awaitility-2.0.0.jar:0.0.0]
         at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
         at
java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
         at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
         at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
         at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
 Caused by: java.lang.IllegalStateException: BundleContext is no longer
valid
         at
org.eclipse.osgi.internal.framework.BundleContextImpl.checkValid(BundleContextImpl.java:983)
         at
org.eclipse.osgi.internal.framework.BundleContextImpl.getBundle(BundleContextImpl.java:129)
         at
org.eclipse.equinox.internal.region.hook.RegionBundleFindHook.find(RegionBundleFindHook.java:43)
         at
org.eclipse.osgi.internal.framework.BundleContextImpl$2.call(BundleContextImpl.java:227)
         at
org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHookPrivileged(ServiceRegistry.java:1280)
         ... 14 more

Bug: 7981 related later proper solution
Change-Id: I516c0f6c4e9ee85f0c753cb4b58a0b53fc22c7ea
Signed-off-by: Michael Vorburger <vorburger@redhat.com>
Signed-off-by: Robert Varga <robert.varga@pantheon.tech>